# Fastfile
default_platform(:ios)

platform :ios do
  desc "Run unit tests"
  lane :test do
    run_tests(
      project: "CookWhat.xcodeproj",
      devices: ["iPhone 15 Pro"],
      scheme: "CookWhat", # Use the app's scheme
      skip_testing: ["CookWhatUITests/*"] # Ignore UI tests
    )
  end

  desc "Build and upload to TestFlight"
  lane :beta do
    build_app(project: "CookWhat.xcodeproj", scheme: "CookWhat")
    upload_to_testflight
  end
end